const translate = {
    en: {
        passw: 'Password',
        emailfield: 'Enter your email',
        passfield: 'Enter your password',
        recopass: 'I forgot my password',
        fblogin: 'login with facebook',
        glogin: 'login with google',
        createacc: 'CREATE AN ACCOUNT',
        passalert: 'User does not exist or password is incorrect!',
        erroralert: 'An error occurred',
        cancelalert: 'The user canceled',

        welcome:'Welcome',
        phrase:'Let\'s begin creating your account',
        fullname:'Full Name',
        rpassw:'Repeat the password',
        next:'NEXT',
        verpass:'"Please check the passwords provided!", "The passwords provided are not the same!\n\nTry again!"',
        start: 'START',

        namequestion: 'How would you like to be called?',
        bikequestion: 'What\'s your bike',
        name: 'Name',
        modelfield:'Enter your bike model',
        professionquestion: 'What\'s your profession?',
        professionfield: 'Profession',
        birthquestion: 'What is your date of birth?',
        birthselect:'Tap here to select your date of birth',
        readandacc:'I read and accept the',
        termsand:'Terms & Conditions',
        createnewacc: 'CREATE NEW ACCOUNT',

        message: 'Message',
        followers: 'Followers',
        following: 'Following',
        notification: 'Notification',
        editprofile: 'Edit profile',
        configurations: 'Settings',
        logout: 'Logout',

        mostliked:'Most Liked',

        passwrecover: 'Password Recovery',
        passwrphrase: 'Let\'s recover your password',

        sharepost: 'Share Post',
        sharechoose: 'Choose what to share',
        sharephrase:'shared this post through the LifWeb app. Join us!',
        exportimg: 'Export Image',
        sharetext: 'Share Text',
        ha: '',
        minutes:' minutes ago',
        hours:' hours ago',
        days:' days ago',
        sharedfrom: 'Shared From',
        likedby: 'Liked by',
        repostpost: 'Repost Post?',
        repostphrase: 'Are you sure you want to repost this post?',
        repost:'Repost',
        cancel:'Cancel',
        deletepost: 'Delete Post',
        delete: 'Delete',
        deletequestion:'Are you sure you want to delete this post?',
        editpost: 'Edit Post',

        postedcomment:'Your comment has been posted.',
        commenterror:'Comment function error.',
        typecomment:'Enter your comment ...',
        deletecomment:'Delete comment?',
        delcommentphrase:'Are you sure you want to delete this comment?',

        search: 'Search',

        follow: 'Follow',
        unfollow: 'Unfollow',
        searchquest:'What are you looking for?',
        people: 'People',
        clubs: 'Clubs',
        city: 'City',
        biketype: 'Bike Type',

        typehere: 'Type here...',


        language:'Language',
        readphrase:'Leia antes nossa política de privacidade',
        deleteacc:'DELETE ACCOUNT',
        contactus: 'CONTACT US',
        deleteaccquest:'Are you sure you want to Delete your account?',

        completereg:'Complete your registration',
        zipcode:'Zip code',
        street:'Street',
        number:'Number',
        citystate:'City/State',
        phone:'Phone',
        bloodtype:'Blood type',
        update:'UPDATE',

        bikebrand:'BIKE BRAND',
        model:'Model',
        year:'Year',
        profile:'Profile',
        coverprofile:'PROFILE COVER',
        profession:'Profession',
        comment:' comment',
        see:'See ',

      },
      pt: {
        passw: 'Senha',
        emailfield: 'Informe seu email',
        passfield: 'Informe sua senha',
        recopass: 'Esqueci minha senha',
        fblogin: 'entrar com o facebook',
        glogin: 'entrar com o google',
        createacc: 'CRIAR UMA CONTA',
        passalert: 'O usuário não existe ou a senha está incorreta!',
        erroralert: 'Ocorreu um erro',
        cancelalert: 'O usuário cancelou',

        welcome:'Seja Bem Vindo(a)',
        phrase:'Vamos iniciar a criação da sua conta',
        fullname:'Nome Completo',
        rpassw:'Repita a senha',
        next: 'PRÓXIMO',
        verpass:'"Verifique as senhas inseridas!", "As senhas inseridas não são iguais!\n\nTente outra vez!"',
        start: 'INICIO',

        namequestion: 'Como você gostaria de ser chamado?',
        bikequestion: 'Qual a sua moto?',
        name: 'Nome',
        modelfield: 'Escreva o modelo da moto',
        professionquestion: 'Qual a sua profissão?',
        professionfield:'Profissão',
        birthquestion:'Qual a sua data de nascimento?',
        brithselect: 'Toque aqui para selecionar sua data de nascimento',
        readandacc:'Eu li e aceito os',
        termsand:'Termos & Condições',
        createnewacc: 'CRIAR NOVA CONTA',
        
        mensage: 'Mensagem',
        followers: 'Seguidores',
        following: 'Seguindo',
        notification: 'Notificação',
        editprofile: 'Editar Perfil',
        configurations: 'Configurações',
        logout: 'Fazer Logoff',

        mostliked: 'Mais Curtido',

        passwrecover: 'Recuperação de senha',
        passwrphrase: 'Vamos recuperar a sua senha',

        sharepost: 'Compartilhar Post',
        sharechoose: 'Escolha o Compartilhamento',
        sharephrase:'Compartilhou esta postagem através do app LifWeb. Junte-se a nos!',
        exportimg: 'Exporta Imagem',
        sharetext: 'Compartilhar Texto',
        ha: 'Há ',
        minutes:' minutos',
        hours:' horas',
        days:' dias',
        sharedfrom: 'Compartilhado de',
        likedby: 'Curtido por',
        repostpost: 'Repostar Post?',
        repostphrase: 'Você tem certeza que deseja repostar esta postagem?',
        repost: 'Repostar',
        cancel: 'Cancelar',
        deletepost: 'Excluir Post',
        editpost: 'Editar Post',

        postedcomment:'Seu comentário foi postado.',
        commenterror:'Erro na função comentar.',
        typecomment:'Digite seu comentário...',
        deletecomment:'Excluir comentário?',
        delcommentphrase:'Você tem certeza que deseja excluir este comentário?',

        search:'Buscar',

        follow: 'Seguir',
        unfollow: 'Deixar de Seguir',

        searchquest:'O que você procura?',
        people: 'Pessoas',
        clubs: 'Clubes',
        city: 'Cidade',
        biketype: 'Tipo de moto',

        typehere:'Digite aqui...',

        language:'Linguagem',
        readphrase:'Leia antes nossa política de privacidade',
        deleteacc:'EXCLUIR CONTA',
        contactus: 'FALE CONOSCO',
        deleteaccquest:'Você tem certeza que deseja Excluir sua conta?',

        completereg:'Complete seu cadastro',
        zipcode:'CEP',
        street:'Rua',
        number:'Número',
        citystate:'Cidade/Estado',
        phone:'Telefone',
        bloodtype:'Tipo Sanguíneo',

        update:'ATUALIZAR',
        bikebrand:'MARCA DA MOTO',
        model:'Modelo',
        year:'Ano',
        profile:'Perfil',
        coverprofile:'CAPA PERFIL',
        profession:'Profissão',
        comment:' comentário',
        see:'Ver ',
        


      },
      es: {
        passw: 'Contraseña',
        emailfield: 'Ingrese su correo electrónico',
        passfield: 'Ingrese su contraseña',
        recopass: 'Olvidé mi contraseña',
        fblogin: 'iniciar sesión con facebook',
        glogin: 'iniciar sesión con google',
        createacc: 'crear una cuenta',
        passalert: '¡El usuario no existe o la contraseña es incorrecta!',
        erroralert: 'Se ha producido un error',
        cancelalert: 'El usuario ha cancelado',


        welcome: 'Bienvenido',
        phrase: "Comencemos a crear su cuenta",
        fullname: 'Nombre completo',
        passw: 'Contraseña',
        rpassw: 'Repetir contraseña',
        next: 'siguiente',
        verpass: '"¡Comprueba las contraseñas introducidas!", "¡Las contraseñas introducidas no son las mismas! \ n \ n¡Inténtalo de nuevo!"',
        inicio: 'INICIO',


        namequestion: '¿Cómo te gustaría que te llamaran?',
        bikequestion: '¿Cuál es tu motocicleta?',
        name: 'nombre',
        modelfield: 'Escribe el modelo de la motocicleta',
        professionquestion: '¿Cuál es su profesión?',
        professionfield: 'Profesión',
        birthquestion: '¿Cuál es su fecha de nacimiento?',
        brithselect: 'Toque aquí para seleccionar su fecha de nacimiento',
        readandacc: 'Los leo y los acepto',
        termsand: 'Términos y condiciones',
        createnewacc: 'CREAR NUEVA CUENTA',

        mensage: 'Mensaje',
        followers: 'Seguidores',
        following: 'Seguidores',
        notification: 'Notificación',
        editprofile: 'Editar perfil',
        configurations: 'Configuración',
        logout: 'Cerrar sesión',


        mostliked: 'Más Gustado',

        passwrecover: 'Recuperación de contraseña',
        passwrphrase: 'Recuperemos su contraseña',

        sharepost: 'Compartir publicación',
        sharechoose: 'Elegir compartir',
        exportimg: 'Exportar imagen',
        sharetext: 'Compartir texto',
        ha: 'Hace ',
        minutes: 'minutos',
        hours: 'horas',
        days: 'días',
        sharedfrom: 'Compartido desde',
        likesby: 'Me gustó',
        repostpost: '¿Repost Post?',
        repostphrase: '¿Estás seguro de que quieres volver a publicar esta publicación?',
        repost: 'Volver a publicar',
        cancel: 'Cancelar',
        deletepost: 'Eliminar publicación',
        editpost: 'Editar publicación',

        postedcomment: 'Su comentario ha sido publicado.',
        commenterror: 'Error en la función de comentario.',
        typecomment: 'Escribe tu comentario ...',
        deletecomment: '¿Eliminar comentario?',
        delcommentphrase: '¿Está seguro de que desea eliminar este comentario?',

        search: 'Buscar',

        follow: 'sigue',
        unfollow: 'Dejar de seguir',

        searchquest: '¿Qué estás buscando?',
        people:'gente',
        clubs: 'Clubes',
        city: 'Ciudad',
        biketype: 'Tipo de motocicleta',

        typehere: 'Escriba aquí ...',

        language: 'Linguagem',
        readphrase: 'Lea primero nuestra política de privacidad',
        deleteacc: 'BORRAR CUENTA',
        contactus: 'HABLAR CON NOSOTROS',
        deleteaccquest: '¿Está seguro de que desea eliminar su cuenta?',

        completereg: 'Complete su registro',
        zipcode:'Código postal',
        street: 'Calle',
        number: 'Número',
        citystate: 'Ciudad / Estado',
        phone: 'Teléfono',
        bloodtype: 'Tipo de sangre',

        update: 'ACTUALIZAR',
        bikebrand: 'MARCA DE LA MOTO',
        model: 'Modelo',
        year: 'Año',
        profile: 'Perfil',
        coverprofile: 'CAPA DE PERFIL',
        profession: 'Profesión',
        comment: 'comentario',
        see: 've',

        },

        
}

export default translate